### ISSUE TITLE
Doesn't work with Sprockets 3.0

### ISSUE THREAD

**Issue by GBH** [mahipal/jade-rails#2]
Seems that this gem is not registering itself correctly anymore. Had to downgrade sprockets to v 2.12.

**Comment by baburdick** [comment]
@GBH: Any plans to issue a pull request for your changes? (https://github.com/GBH/jade-rails/commit/12b2f5b34720a23bc6148f0a907df9018a1c2492)

@mahipal: Any plans to pull in @GBH's changes to remedy this?

cc: @avolosenko

**Comment by GBH** [comment]
@baburdick My fork kills compatibility with sprockets lower than 3.0. It's possible to add that, but I just didn't want to spend too much time on that. Also I broke all tests.

I wanted to make a new gem... `pug-rails`? But i ran into issues with Sprockets and how to make use of its JST processor. It's all kinds of weird.

**Comment by paulrex** [comment]
Yeah, we should keep backwards-compatibility.

I haven't had time to look into this yet. I'll try to set aside some time this weekend or next weekend. In the meantime, always happy to review/merge pull requests.

**Comment by paulrex** [comment]
Just released v1.11.0.1 which adds Sprockets 3 compatibility while maintaining Sprockets 2 compatibility.

Give it a try. Let me know how it goes.
