### ISSUE TITLE
Error: undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by avolosenko** [mahipal/jade-rails#3]
Hey

I have the same issue as in https://github.com/mahipal/jade-rails/issues/1

On jade-rails-1.11.0.0/lib/jade/template.rb:40:in `evaluate':

jade_config = app_level_config.merge(options)

I'm using rails Rails 4.1.15

**Comment by vill** [comment]
`RAILS_ENV=production bundle exec rake assets:precompile` - `NoMethodError: undefined method merge for nil:NilClass`

If set `config.cache_classes = false` in `production.rb` then `RAILS_ENV=production bundle exec rake assets:precompile` without errors.

**Comment by paulrex** [comment]
Just released v1.11.0.1. Everything works smoothly with this new version in a fresh Rails 4.2 app, so just run `bundle update jade-rails` and this should be fixed.
