### ISSUE TITLE
How can I lose the `templates` prefix

### ISSUE THREAD

**Issue by itay-grudev** [mahipal/jade-rails#4]
I'd like to switch to `jade-rails` but my app currently invokes templates without the `templates/` prefix, like so:

```js
JST['products/product']
```
instead of
```js
JST['templates/products/product']
```

And since the `templates/` prefix is quite redundant, is there a way to get rid of it?

**Comment by yivo** [comment]
This feature is controlled by sprockets processor https://github.com/rails/sprockets/blob/master/lib/sprockets/jst_processor.rb#L45

**Comment by yivo** [comment]
Personally I store templates in `app/assets/templates` and I have `JST['products/product']` naming. Where do you store templates?

**Comment by itay-grudev** [comment]
`app/assets/javascripts/templates/`

**Comment by yivo** [comment]
I have just tested with my own installation and I am having `JST['templates/products/product']` too when stored at `app/assets/javascripts/templates`.

You can either monkey patch `Sprockets::JstProcessor#call(input)` to behave differently for templates, either move templates to `app/assets/templates`.

**Comment by yivo** [comment]
This issue is not related to jade-rails.

**Comment by itay-grudev** [comment]
Hmm. Interesting... Thanks.
